### PR TITLE
Upgrade ember dependencies and remove bower

### PR DESCRIPTION
**Pull request by danwenzel**
- Upgrades Ember to 2.18
- Moves Ember out of Bower and removes Bower
- Upgrades CircleCI to 2.0 and uses Yarn

### CODE REVIEW

**Comment by danwenzel** [comment]
Can't seem to get Circle to be happy.  Weird error.  I'll have to look at this later.

**Comment by danwenzel** [comment]
@marxsk - Finally got this one working.  Had to also upgrade CircleCI to 2.0

**Comment by marxsk** [comment]
@danwenzel great. Can you please merge those patches together (or to a smaller amount of patches). There are commits that adds/removes same lines (e.g. npm upgrade / npm remove). Thanks.

I will wait for this PR before next release.

**Comment by danwenzel** [comment]
@marxsk - I'd be ok if you just squash 'n merged this whole thing - unless you were needing something to be split up?

**Comment by marxsk** [comment]
@danwenzel thanks, done

**Pull request merged**
