### PR TITLE
Enabling form-for to be used in engines

### PR DESCRIPTION
**Pull request by topaxi**
Tried to use ember-form-for in an in-repo engine, the initializer crashed with `app.__container__ is undefined`.

I'm not sure if this fix is the right approach.

### CODE REVIEW

**Comment by marxsk** [comment]
@topaxi  I have not used Ember Engines yet, can you create a simple test for it?

**Comment by topaxi** [comment]
I'm sorry I didn't get back to you two weeks ago, I'm still not sure if this fix was the right approach and I'm also not sure how I'd create a simple test for this. Or did you mean to create a minimal test-app to reproduce the error?

**Comment by marxsk** [comment]
@topaxi There is also similar PR #193 which is based on similar solution, so at least it works :)

I would like to have an acceptance test (or any other) that will work so we don't have regression with ember-engines.

**Comment by topaxi** [comment]
Ah I see, I did not see the other PR :) Sadly I'm currently not using anything Ember related so this isn't a high priority to me. If the other PR stalls, ping me and I'll try to find an evening where I can try to come up with an acceptance test for this or the other PR. :+1:

**Pull request closed without merging**
