### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by amiel**
Hi, I realize this project is not currently under active maintenance.

I believe I've fixed the test suite so that anyone continuing to develop on `ember-form-for` can work from green.

I believe the current issues stem from [this change](https://github.com/martndemus/ember-form-for/pull/169), although I don't fully know the history.

The approach here is to run the new initializer that injects i18n after registering the i18n stub.

Since this happens in a few places, I've also introduced a support file with a helper that does just this.

Thanks for considering merging this as I think others forking this repository might find it helpful.

### CODE REVIEW

**Comment by amiel** [comment]
Darn, the tests passed for me locally, but I guess there are some issues with the `ember-release` scenario. I'll look in to that again later this week.

**Comment by danwenzel** [comment]
Hi @amiel .  Thanks for working on this.  Any updates?

**Comment by amiel** [comment]
@danwenzel Yeah. I basically got everything working for older versions of Ember (everything `< 2.18`), which is actually fine for our app.

However, 2.18+ all fail and I think it's related to the ember-try configuration with bower.

**Comment by danwenzel** [comment]
@amiel - `ember-try` recently released v1.0.0-beta.1, which may fix that issue.  Worth a shot...

**Comment by amiel** [comment]
@danwenzel I'll take a look during my next open source work time; thanks!

**Comment by amiel** [comment]
@martndemus Any chance you'd be in to merging this?

**Comment by marxsk** [comment]
@amiel Thanks for fixing those tests.

**Pull request merged**
