### PR TITLE
Upgrade ember-one-way-controls for Ember 3 support

### PR DESCRIPTION
**Pull request by danwenzel**
This is required to avoid an error in Ember 3 when using textareas: https://github.com/DockYard/ember-one-way-controls/issues/185.

### CODE REVIEW

**Comment by marxsk** [comment]
Thanks

**Comment by danwenzel** [comment]
Thanks for merging this, @marxsk !  Are we ready to cut a release?  Maybe we can call this a stable release, and get out of the alphas?

**Comment by marxsk** [comment]
@danwenzel I want to check if there are no more issues with double rendering (and hopefully add test for Ember Engines (as posted PR are simple enough)

**Comment by danwenzel** [comment]
@marxsk - Any chance we could cut a release with this now?  It would be nice to at least get Ember 3 support for those of us who don't use Ember Engines.

**Comment by marxsk** [comment]
@danwenzel Next beta will be on Tuesday.

**Comment by danwenzel** [comment]
@marxsk - Thank you for cutting the new release!  When are you planning on publishing it to npm?

**Comment by marxsk** [comment]
@danwenzel done, I have obtained a rights to do it yesterday. Next releases will be done immediately.

**Pull request merged**
